[project]
name = "python-git-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "icecream>=2.1.4",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
